### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by Keane-Tan** [cms-svj/SVJTaggerNN#17]
According to the discussion on this link: https://github.com/pytorch/pytorch/issues/69894
it seems like the problem is related to the newer version of setuptools (where we get distutils from) .
If we install the older setuptools (setuptools==59.5.0), it fixes the issue.

**Comment by kpedro88** [comment]
Can you explain where/how you saw this error?

**Comment by Keane-Tan** [comment]
Sorry for not being clear when I opened the issue.
I saw this error just by running 
python train.py --outf logTest
after following the setup outlined in the README.


The full error message looks like this:
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from dataset import RootDataset, get_sizes
  File "/uscms_data/d3/keanet/SVJ/TaggerTest/SVJTaggerNN/dataset.py", line 2, in <module>
    import uproot as up
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_99cuda/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/uproot/__init__.py", line 116, in <module>
    from uproot.rootio import open, xrootd, http
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_99cuda/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/uproot/rootio.py", line 27, in <module>
    import uproot_methods.classes
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_99cuda/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/uproot_methods/__init__.py", line 5, in <module>
    from uproot_methods.classes.TVector2 import TVector2, TVector2Array
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_99cuda/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/uproot_methods/classes/TVector2.py", line 8, in <module>
    import awkward.array.jagged
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_99cuda/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/awkward/__init__.py", line 8, in <module>
    if distutils.version.LooseVersion(numpy.__version__) < distutils.version.LooseVersion("1.13.1"):
AttributeError: module 'distutils' has no attribute 'version'

So it was in the awkward's __init__.py file where disutils.version is used, and it seems like the new version of setuptools does not support disutils.version anymore...

**Comment by kpedro88** [comment]
It looks like this is coming from uproot_methods, which is an outdated package now (it went with uproot3, which is deprecated in favor of uproot4). We should make sure we've removed all usage of it (e.g. writing histograms to files, which can now be done with uproot4) and then this error should go away.
